---
title: "ENSAP"
author: "granpiero"
date: "2026-02-03"
description: "ENSAP procedures"
categories: [procedure]
editor: 
  markdown: 
    wrap: sentence
---

> ENSAP procedures

### **Sommaire**

1.  [Informez votre centre de gestion des retraites](https://retraitesdeletat.gouv.fr/retraite/ma-pension-letranger/les-demarches#informez-centre-gestion-retraites)

**=> informer par messagerie ENSAP  Limoges de mon changement d'adresse permanente , qui transfère la gestion de ma retrait à Nantes.** le mode de paiement de votre pension reste au RIB connu en France.

2.  [Informez votre mutuelle](https://retraitesdeletat.gouv.fr/retraite/ma-pension-letranger/les-demarches#informez-mutuelle)

3.  [Contactez le service des impots](https://retraitesdeletat.gouv.fr/retraite/ma-pension-letranger/les-demarches#contactez-service-impots)

Par téléphone +33 (0) 1 72 95 20 42 lundi au vendredi de 9h à 16h

Par messagerie Via votre messagerie sécurisée sur votre compte personnel

Par courrier 10 rue du Centre TSA 10010 93465 Noisy-Le-Grand Cedex

4.  [Pour toute question sur votre dossier](https://retraitesdeletat.gouv.fr/retraite/ma-pension-letranger/les-demarches#question-dossier)


Depuis début 2024, le gouvernement a durci les règles concernant les retraités français vivant à l'étranger.
L'idée ?
Mettre fin aux abus et mieux encadrer le versement des prestations sociales.
En clair, si vous passez plus de 183 jours par an hors de France, vous êtes désormais considéré comme non-résident.

Les administrations croisent désormais les données fiscales, bancaires et sociales pour vérifier la cohérence de votre situation.
Si des incohérences apparaissent, mieux vaut avoir tout déclaré correctement sous peine de voir certains versements suspendus.

1.  Déclarer officiellement votre **pays de résidence**

2.  Mettre à jour ses **coordonnées bancaires et fiscales** Si vous percevez votre retraite sur un compte étranger – ce qui est parfaitement autorisé – il faut le signaler.

3.  Envoyer son **certificat de vie annuel**… à temps C’est l’un des points les plus surveillés.
    Le certificat de vie, demandé une fois par an (ou plus selon les caisses), doit être transmis dans les délais, signé par une autorité locale ou un consulat.

4.  Prévenir l’**assurance maladie** Si vous êtes affilié à l’Assurance Maladie, il est également nécessaire de l’informer de votre départ.

**Fin de la prise en charge automatique des soins en France** Vos droits à l’assurance maladie française sont **suspendus** si vous êtes considéré comme résident à l’étranger.

### Contactez le service des impots

Pour toute question relative à votre imposition, vous êtes invité à contacter le service des impôts des particuliers (SIP) des non résidents :

Par téléphone : (+33) 01 72 95 20 42, du lundi au vendredi de 9h à 16h.

En ligne :
En qualité de non-résident, vous avez également possibilité de prendre rendez-vous pour un entretien téléphonique relatif à votre situation personnelle, avec le service en charge de votre dossier, à l'adresse suivante : https://www.impots.gouv.fr/portail/contacts ou via votre messagerie sécurisée.
Ce service est également ouvert aux primo-déclarants, c'est à dire les personnes qui déclarent leur revenu pour la première fois en France.

Par courrier :
Direction des impôts des non-résidents
10, rue du Centre
TSA 10010
93465 Noisy-Le-Grand Cedex